export const products = [
  // Crypto-Trading Bots
  {
    id: '3commas',
    name: '3Commas',
    description: 'Advanced crypto trading bot with smart trading features',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'cryptohawk',
    name: 'CryptoHawk',
    description: 'AI-powered cryptocurrency trading automation platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'kryll',
    name: 'Kryll',
    description: 'Visual crypto trading bot builder and marketplace',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'haasonline',
    name: 'HaasOnline',
    description: 'Professional-grade crypto trading automation',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'napbots',
    name: 'NapBots',
    description: 'Automated crypto trading strategies platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'quadency',
    name: 'Quadency',
    description: 'Unified crypto trading and portfolio management',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'shrimpy',
    name: 'Shrimpy',
    description: 'Social crypto trading and portfolio rebalancing',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'zignaly',
    name: 'Zignaly',
    description: 'Profit-sharing crypto trading platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'bitsgap',
    name: 'Bitsgap',
    description: 'Unified crypto trading platform with automation',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'cryptorg',
    name: 'Cryptorg',
    description: 'Automated crypto trading bot platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'trality',
    name: 'Trality',
    description: 'Python-based crypto trading bot platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'coinrule',
    name: 'Coinrule',
    description: 'No-code crypto trading automation platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'stoic',
    name: 'Stoic',
    description: 'AI-powered crypto trading automation',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'mudrex',
    name: 'Mudrex',
    description: 'Crypto trading bot marketplace and automation',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'coinigy',
    name: 'Coinigy',
    description: 'Crypto trading and portfolio management platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'cornix',
    name: 'Cornix',
    description: 'Telegram-based crypto trading automation',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'wundertrading',
    name: 'WunderTrading',
    description: 'Professional crypto trading automation platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'tradesanta',
    name: 'TradeSanta',
    description: 'Automated crypto trading strategies platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'pionex',
    name: 'Pionex',
    description: 'Free crypto trading bot platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },
  {
    id: 'margin-de',
    name: 'Margin.de',
    description: 'Advanced crypto trading automation platform',
    useCases: ['automation'],
    industries: ['finance'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'api',
    pricingModel: 'subscription',
  },

  // Legal Smart-Contract Analyzers
  {
    id: 'lawgeex',
    name: 'LawGeex',
    description: 'AI-powered contract review and analysis platform',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'contractpodai',
    name: 'ContractPodAi',
    description: 'Intelligent contract management and analysis system',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'klarity',
    name: 'Klarity',
    description: 'AI-powered contract review and analysis',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'kira-systems',
    name: 'Kira Systems',
    description: 'Machine learning contract analysis platform',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'ebrevia',
    name: 'eBrevia',
    description: 'AI-powered contract analysis and due diligence',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'luminance',
    name: 'Luminance',
    description: 'AI-powered legal document analysis',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'thoughtriver',
    name: 'ThoughtRiver',
    description: 'Contract pre-screening and analysis platform',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'ayfie',
    name: 'Ayfie',
    description: 'Document analysis and contract review platform',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'eigen-technologies',
    name: 'Eigen Technologies',
    description: 'Document analysis and extraction platform',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'textiq',
    name: 'TextIQ',
    description: 'AI-powered legal document analysis',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'clause',
    name: 'Clause',
    description: 'Smart contract and legal document platform',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },
  {
    id: 'lexcheck',
    name: 'LexCheck',
    description: 'AI-powered contract review and analysis',
    useCases: ['data-analysis'],
    industries: ['legal'],
    ioTypes: ['text-to-text'],
    customizationLevel: 'sdk',
    pricingModel: 'subscription',
  },

  // Medical AI Assistants
  {
    id: 'abridge',
    name: 'Abridge',
    description: 'AI-powered medical conversation recording and analysis',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'amboss-ai',
    name: 'Amboss AI',
    description: 'Medical knowledge platform with AI assistance',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'luma-health',
    name: 'Luma Health',
    description: 'Patient engagement and communication platform',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'nuance-dragon',
    name: 'Nuance Dragon Medical',
    description: 'Voice recognition for medical documentation',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'buoy-health',
    name: 'Buoy Health',
    description: 'AI-powered symptom checker and health assistant',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'isabel-healthcare',
    name: 'Isabel Healthcare',
    description: 'Clinical decision support system',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'sensely',
    name: 'Sensely',
    description: 'Virtual health assistant platform',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'k-health',
    name: 'K Health',
    description: 'AI-powered primary care platform',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'babylon-health',
    name: 'Babylon Health',
    description: 'Digital health service with AI assistance',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'prognos',
    name: 'Prognos',
    description: 'AI-powered health analytics platform',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'caption-health',
    name: 'Caption Health',
    description: 'AI-guided ultrasound platform',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },
  {
    id: 'olive-ai',
    name: 'Olive AI',
    description: 'Healthcare automation platform',
    useCases: ['audio-speech'],
    industries: ['healthcare'],
    ioTypes: ['audio-to-text'],
    customizationLevel: 'api',
    pricingModel: 'free',
  },

  // Voice & Speech Services
  {
    id: 'murf-ai',
    name: 'Murf.ai',
    description: 'AI voice generator for natural-sounding speech',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'descript-overdub',
    name: 'Descript Overdub',
    description: 'AI voice cloning and editing platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'resemble-ai',
    name: 'Resemble AI',
    description: 'AI voice cloning and generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'replica-studios',
    name: 'Replica Studios',
    description: 'AI voice actors and generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'play-ht',
    name: 'Play.ht',
    description: 'Text-to-speech and voice generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'lovo',
    name: 'LOVO',
    description: 'AI voice generator and text-to-speech platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'speechify',
    name: 'Speechify',
    description: 'Text-to-speech and voice generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'wellsaid-labs',
    name: 'WellSaid Labs',
    description: 'AI voice generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'ispeech',
    name: 'iSpeech',
    description: 'Text-to-speech and voice generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'voicify',
    name: 'Voicify',
    description: 'AI voice cloning and generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'voicemod',
    name: 'VoiceMod',
    description: 'Real-time voice changer and generator',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
  {
    id: 'readspeaker',
    name: 'ReadSpeaker',
    description: 'Text-to-speech and voice generation platform',
    useCases: ['audio-speech'],
    industries: ['marketing'],
    ioTypes: ['text-to-audio'],
    customizationLevel: 'widgets',
    pricingModel: 'pay-per-use',
  },
]; 